console.log("Hello world")
console.log("2")
console.log(2+2)
console.log(2*5)
console.log(10-3)
console.log(10/3)
console.log(10%3)
console.log(9%2)
console.log(10%2)
console.log(true || true)
console.log(false || true)
console.log(false || false)
console.log(true && true)
console.log(false && true)
console.log(false && false)